services:
  clash-configurator:
    image: shenbourne/clash-configurator:latest
    container_name: clash-configurator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=*
    volumes:
      # 配置文件
      - ./data/configs:/app/server/data/configs
      # 规则集
      - ./data/rule-sets:/app/server/data/rule-sets
      # 临时文件
      - ./data/temp:/app/server/data/temp
    restart: unless-stopped